/********************************************************************************
** Form generated from reading UI file 'ctrlvisionlifesignalform.ui'
**
** Created: Sat Oct 14 09:26:49 2017
**      by: Qt User Interface Compiler version 4.6.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CTRLVISIONLIFESIGNALFORM_H
#define UI_CTRLVISIONLIFESIGNALFORM_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CtrlVisionLifesignalForm
{
public:
    QLabel *name1;
    QLabel *vision1;
    QLabel *lifesignal1;
    QLabel *label3;
    QLabel *label2;
    QLabel *label1;
    QLabel *label6;
    QLabel *label5;
    QLabel *label4;
    QLabel *label9;
    QLabel *label8;
    QLabel *label7;
    QLabel *lifesignal2;
    QLabel *vision2;
    QLabel *name2;
    QLabel *lifesignal3;
    QLabel *vision3;
    QLabel *name3;
    QLabel *lifesignal4;
    QLabel *vision4;
    QLabel *name4;
    QLabel *lifesignal5;
    QLabel *vision5;
    QLabel *name5;
    QLabel *lifesignal6;
    QLabel *vision6;
    QLabel *name6;
    QLabel *lifesignal7;
    QLabel *vision7;
    QLabel *name7;
    QLabel *lifesignal8;
    QLabel *vision8;
    QLabel *name8;
    QLabel *lifesignal5_2;
    QLabel *lifesignal6_2;
    QLabel *name8_2;
    QLabel *vision4_2;
    QLabel *lifesignal8_2;
    QLabel *name7_2;
    QLabel *vision3_2;
    QLabel *lifesignal1_2;
    QLabel *name4_2;
    QLabel *name6_2;
    QLabel *lifesignal3_2;
    QLabel *vision6_2;
    QLabel *vision7_2;
    QLabel *lifesignal2_2;
    QLabel *lifesignal4_2;
    QLabel *name5_2;
    QLabel *vision1_2;
    QLabel *name3_2;
    QLabel *name2_2;
    QLabel *vision2_2;
    QLabel *vision8_2;
    QLabel *vision5_2;
    QLabel *name1_2;
    QLabel *lifesignal7_2;
    QLabel *lifesignal5_3;
    QLabel *lifesignal6_3;
    QLabel *name8_3;
    QLabel *vision4_3;
    QLabel *lifesignal8_3;
    QLabel *name7_3;
    QLabel *vision3_3;
    QLabel *lifesignal1_3;
    QLabel *name4_3;
    QLabel *name6_3;
    QLabel *lifesignal3_3;
    QLabel *vision6_3;
    QLabel *vision7_3;
    QLabel *lifesignal2_3;
    QLabel *lifesignal4_3;
    QLabel *name5_3;
    QLabel *vision1_3;
    QLabel *name3_3;
    QLabel *name2_3;
    QLabel *vision2_3;
    QLabel *vision8_3;
    QLabel *vision5_3;
    QLabel *name1_3;
    QLabel *lifesignal7_3;
    QLabel *name9;
    QLabel *vision9;
    QLabel *vision9_2;
    QLabel *vision9_3;
    QLabel *name9_2;
    QLabel *lifesignal9_2;
    QLabel *lifesignal9;
    QLabel *lifesignal9_3;
    QLabel *name9_3;
    QLabel *name10;
    QLabel *vision10;
    QLabel *vision10_2;
    QLabel *vision10_3;
    QLabel *name10_2;
    QLabel *lifesignal10_2;
    QLabel *lifesignal10;
    QLabel *lifesignal10_3;
    QLabel *name10_3;
    QLabel *name11;
    QLabel *lifesignal11;
    QLabel *vision11;
    QLabel *name12;
    QLabel *lifesignal12;
    QLabel *vision12;
    QLabel *name11_2;
    QLabel *vision12_2;
    QLabel *lifesignal12_2;
    QLabel *vision11_2;
    QLabel *name12_2;
    QLabel *lifesignal11_2;
    QLabel *name11_3;
    QLabel *vision12_3;
    QLabel *lifesignal12_3;
    QLabel *vision11_3;
    QLabel *name12_3;
    QLabel *lifesignal11_3;

    void setupUi(QWidget *CtrlVisionLifesignalForm)
    {
        if (CtrlVisionLifesignalForm->objectName().isEmpty())
            CtrlVisionLifesignalForm->setObjectName(QString::fromUtf8("CtrlVisionLifesignalForm"));
        CtrlVisionLifesignalForm->resize(700, 410);
        CtrlVisionLifesignalForm->setStyleSheet(QString::fromUtf8("QLabel\n"
"{\n"
"	font: 12px ;\n"
"	color: black;\n"
"	border:2px solid black;\n"
"	background-color:rgb(216,216,216);\n"
"}"));
        name1 = new QLabel(CtrlVisionLifesignalForm);
        name1->setObjectName(QString::fromUtf8("name1"));
        name1->setGeometry(QRect(20, 40, 91, 31));
        name1->setAlignment(Qt::AlignCenter);
        vision1 = new QLabel(CtrlVisionLifesignalForm);
        vision1->setObjectName(QString::fromUtf8("vision1"));
        vision1->setGeometry(QRect(110, 40, 71, 31));
        vision1->setAlignment(Qt::AlignCenter);
        lifesignal1 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal1->setObjectName(QString::fromUtf8("lifesignal1"));
        lifesignal1->setGeometry(QRect(180, 40, 61, 31));
        lifesignal1->setAlignment(Qt::AlignCenter);
        label3 = new QLabel(CtrlVisionLifesignalForm);
        label3->setObjectName(QString::fromUtf8("label3"));
        label3->setGeometry(QRect(180, 10, 61, 31));
        label3->setAlignment(Qt::AlignCenter);
        label2 = new QLabel(CtrlVisionLifesignalForm);
        label2->setObjectName(QString::fromUtf8("label2"));
        label2->setGeometry(QRect(110, 10, 71, 31));
        label2->setAlignment(Qt::AlignCenter);
        label1 = new QLabel(CtrlVisionLifesignalForm);
        label1->setObjectName(QString::fromUtf8("label1"));
        label1->setGeometry(QRect(20, 10, 91, 31));
        label1->setAlignment(Qt::AlignCenter);
        label6 = new QLabel(CtrlVisionLifesignalForm);
        label6->setObjectName(QString::fromUtf8("label6"));
        label6->setGeometry(QRect(400, 10, 61, 31));
        label6->setAlignment(Qt::AlignCenter);
        label5 = new QLabel(CtrlVisionLifesignalForm);
        label5->setObjectName(QString::fromUtf8("label5"));
        label5->setGeometry(QRect(330, 10, 71, 31));
        label5->setAlignment(Qt::AlignCenter);
        label4 = new QLabel(CtrlVisionLifesignalForm);
        label4->setObjectName(QString::fromUtf8("label4"));
        label4->setGeometry(QRect(240, 10, 91, 31));
        label4->setAlignment(Qt::AlignCenter);
        label9 = new QLabel(CtrlVisionLifesignalForm);
        label9->setObjectName(QString::fromUtf8("label9"));
        label9->setGeometry(QRect(620, 10, 61, 31));
        label9->setAlignment(Qt::AlignCenter);
        label8 = new QLabel(CtrlVisionLifesignalForm);
        label8->setObjectName(QString::fromUtf8("label8"));
        label8->setGeometry(QRect(550, 10, 71, 31));
        label8->setAlignment(Qt::AlignCenter);
        label7 = new QLabel(CtrlVisionLifesignalForm);
        label7->setObjectName(QString::fromUtf8("label7"));
        label7->setGeometry(QRect(460, 10, 91, 31));
        label7->setAlignment(Qt::AlignCenter);
        lifesignal2 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal2->setObjectName(QString::fromUtf8("lifesignal2"));
        lifesignal2->setGeometry(QRect(180, 70, 61, 31));
        lifesignal2->setAlignment(Qt::AlignCenter);
        vision2 = new QLabel(CtrlVisionLifesignalForm);
        vision2->setObjectName(QString::fromUtf8("vision2"));
        vision2->setGeometry(QRect(110, 70, 71, 31));
        vision2->setAlignment(Qt::AlignCenter);
        name2 = new QLabel(CtrlVisionLifesignalForm);
        name2->setObjectName(QString::fromUtf8("name2"));
        name2->setGeometry(QRect(20, 70, 91, 31));
        name2->setAlignment(Qt::AlignCenter);
        lifesignal3 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal3->setObjectName(QString::fromUtf8("lifesignal3"));
        lifesignal3->setGeometry(QRect(180, 100, 61, 31));
        lifesignal3->setAlignment(Qt::AlignCenter);
        vision3 = new QLabel(CtrlVisionLifesignalForm);
        vision3->setObjectName(QString::fromUtf8("vision3"));
        vision3->setGeometry(QRect(110, 100, 71, 31));
        vision3->setAlignment(Qt::AlignCenter);
        name3 = new QLabel(CtrlVisionLifesignalForm);
        name3->setObjectName(QString::fromUtf8("name3"));
        name3->setGeometry(QRect(20, 100, 91, 31));
        name3->setAlignment(Qt::AlignCenter);
        lifesignal4 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal4->setObjectName(QString::fromUtf8("lifesignal4"));
        lifesignal4->setGeometry(QRect(180, 130, 61, 31));
        lifesignal4->setAlignment(Qt::AlignCenter);
        vision4 = new QLabel(CtrlVisionLifesignalForm);
        vision4->setObjectName(QString::fromUtf8("vision4"));
        vision4->setGeometry(QRect(110, 130, 71, 31));
        vision4->setAlignment(Qt::AlignCenter);
        name4 = new QLabel(CtrlVisionLifesignalForm);
        name4->setObjectName(QString::fromUtf8("name4"));
        name4->setGeometry(QRect(20, 130, 91, 31));
        name4->setAlignment(Qt::AlignCenter);
        lifesignal5 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal5->setObjectName(QString::fromUtf8("lifesignal5"));
        lifesignal5->setGeometry(QRect(180, 160, 61, 31));
        lifesignal5->setAlignment(Qt::AlignCenter);
        vision5 = new QLabel(CtrlVisionLifesignalForm);
        vision5->setObjectName(QString::fromUtf8("vision5"));
        vision5->setGeometry(QRect(110, 160, 71, 31));
        vision5->setAlignment(Qt::AlignCenter);
        name5 = new QLabel(CtrlVisionLifesignalForm);
        name5->setObjectName(QString::fromUtf8("name5"));
        name5->setGeometry(QRect(20, 160, 91, 31));
        name5->setAlignment(Qt::AlignCenter);
        lifesignal6 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal6->setObjectName(QString::fromUtf8("lifesignal6"));
        lifesignal6->setGeometry(QRect(180, 190, 61, 31));
        lifesignal6->setAlignment(Qt::AlignCenter);
        vision6 = new QLabel(CtrlVisionLifesignalForm);
        vision6->setObjectName(QString::fromUtf8("vision6"));
        vision6->setGeometry(QRect(110, 190, 71, 31));
        vision6->setAlignment(Qt::AlignCenter);
        name6 = new QLabel(CtrlVisionLifesignalForm);
        name6->setObjectName(QString::fromUtf8("name6"));
        name6->setGeometry(QRect(20, 190, 91, 31));
        name6->setAlignment(Qt::AlignCenter);
        lifesignal7 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal7->setObjectName(QString::fromUtf8("lifesignal7"));
        lifesignal7->setGeometry(QRect(180, 220, 61, 31));
        lifesignal7->setAlignment(Qt::AlignCenter);
        vision7 = new QLabel(CtrlVisionLifesignalForm);
        vision7->setObjectName(QString::fromUtf8("vision7"));
        vision7->setGeometry(QRect(110, 220, 71, 31));
        vision7->setAlignment(Qt::AlignCenter);
        name7 = new QLabel(CtrlVisionLifesignalForm);
        name7->setObjectName(QString::fromUtf8("name7"));
        name7->setGeometry(QRect(20, 220, 91, 31));
        name7->setAlignment(Qt::AlignCenter);
        lifesignal8 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal8->setObjectName(QString::fromUtf8("lifesignal8"));
        lifesignal8->setGeometry(QRect(180, 250, 61, 31));
        lifesignal8->setAlignment(Qt::AlignCenter);
        vision8 = new QLabel(CtrlVisionLifesignalForm);
        vision8->setObjectName(QString::fromUtf8("vision8"));
        vision8->setGeometry(QRect(110, 250, 71, 31));
        vision8->setAlignment(Qt::AlignCenter);
        name8 = new QLabel(CtrlVisionLifesignalForm);
        name8->setObjectName(QString::fromUtf8("name8"));
        name8->setGeometry(QRect(20, 250, 91, 31));
        name8->setAlignment(Qt::AlignCenter);
        lifesignal5_2 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal5_2->setObjectName(QString::fromUtf8("lifesignal5_2"));
        lifesignal5_2->setGeometry(QRect(400, 160, 61, 31));
        lifesignal5_2->setAlignment(Qt::AlignCenter);
        lifesignal6_2 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal6_2->setObjectName(QString::fromUtf8("lifesignal6_2"));
        lifesignal6_2->setGeometry(QRect(400, 190, 61, 31));
        lifesignal6_2->setAlignment(Qt::AlignCenter);
        name8_2 = new QLabel(CtrlVisionLifesignalForm);
        name8_2->setObjectName(QString::fromUtf8("name8_2"));
        name8_2->setGeometry(QRect(240, 250, 91, 31));
        name8_2->setAlignment(Qt::AlignCenter);
        vision4_2 = new QLabel(CtrlVisionLifesignalForm);
        vision4_2->setObjectName(QString::fromUtf8("vision4_2"));
        vision4_2->setGeometry(QRect(330, 130, 71, 31));
        vision4_2->setAlignment(Qt::AlignCenter);
        lifesignal8_2 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal8_2->setObjectName(QString::fromUtf8("lifesignal8_2"));
        lifesignal8_2->setGeometry(QRect(400, 250, 61, 31));
        lifesignal8_2->setAlignment(Qt::AlignCenter);
        name7_2 = new QLabel(CtrlVisionLifesignalForm);
        name7_2->setObjectName(QString::fromUtf8("name7_2"));
        name7_2->setGeometry(QRect(240, 220, 91, 31));
        name7_2->setAlignment(Qt::AlignCenter);
        vision3_2 = new QLabel(CtrlVisionLifesignalForm);
        vision3_2->setObjectName(QString::fromUtf8("vision3_2"));
        vision3_2->setGeometry(QRect(330, 100, 71, 31));
        vision3_2->setAlignment(Qt::AlignCenter);
        lifesignal1_2 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal1_2->setObjectName(QString::fromUtf8("lifesignal1_2"));
        lifesignal1_2->setGeometry(QRect(400, 40, 61, 31));
        lifesignal1_2->setAlignment(Qt::AlignCenter);
        name4_2 = new QLabel(CtrlVisionLifesignalForm);
        name4_2->setObjectName(QString::fromUtf8("name4_2"));
        name4_2->setGeometry(QRect(240, 130, 91, 31));
        name4_2->setAlignment(Qt::AlignCenter);
        name6_2 = new QLabel(CtrlVisionLifesignalForm);
        name6_2->setObjectName(QString::fromUtf8("name6_2"));
        name6_2->setGeometry(QRect(240, 190, 91, 31));
        name6_2->setAlignment(Qt::AlignCenter);
        lifesignal3_2 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal3_2->setObjectName(QString::fromUtf8("lifesignal3_2"));
        lifesignal3_2->setGeometry(QRect(400, 100, 61, 31));
        lifesignal3_2->setAlignment(Qt::AlignCenter);
        vision6_2 = new QLabel(CtrlVisionLifesignalForm);
        vision6_2->setObjectName(QString::fromUtf8("vision6_2"));
        vision6_2->setGeometry(QRect(330, 190, 71, 31));
        vision6_2->setAlignment(Qt::AlignCenter);
        vision7_2 = new QLabel(CtrlVisionLifesignalForm);
        vision7_2->setObjectName(QString::fromUtf8("vision7_2"));
        vision7_2->setGeometry(QRect(330, 220, 71, 31));
        vision7_2->setAlignment(Qt::AlignCenter);
        lifesignal2_2 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal2_2->setObjectName(QString::fromUtf8("lifesignal2_2"));
        lifesignal2_2->setGeometry(QRect(400, 70, 61, 31));
        lifesignal2_2->setAlignment(Qt::AlignCenter);
        lifesignal4_2 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal4_2->setObjectName(QString::fromUtf8("lifesignal4_2"));
        lifesignal4_2->setGeometry(QRect(400, 130, 61, 31));
        lifesignal4_2->setAlignment(Qt::AlignCenter);
        name5_2 = new QLabel(CtrlVisionLifesignalForm);
        name5_2->setObjectName(QString::fromUtf8("name5_2"));
        name5_2->setGeometry(QRect(240, 160, 91, 31));
        name5_2->setAlignment(Qt::AlignCenter);
        vision1_2 = new QLabel(CtrlVisionLifesignalForm);
        vision1_2->setObjectName(QString::fromUtf8("vision1_2"));
        vision1_2->setGeometry(QRect(330, 40, 71, 31));
        vision1_2->setAlignment(Qt::AlignCenter);
        name3_2 = new QLabel(CtrlVisionLifesignalForm);
        name3_2->setObjectName(QString::fromUtf8("name3_2"));
        name3_2->setGeometry(QRect(240, 100, 91, 31));
        name3_2->setAlignment(Qt::AlignCenter);
        name2_2 = new QLabel(CtrlVisionLifesignalForm);
        name2_2->setObjectName(QString::fromUtf8("name2_2"));
        name2_2->setGeometry(QRect(240, 70, 91, 31));
        name2_2->setAlignment(Qt::AlignCenter);
        vision2_2 = new QLabel(CtrlVisionLifesignalForm);
        vision2_2->setObjectName(QString::fromUtf8("vision2_2"));
        vision2_2->setGeometry(QRect(330, 70, 71, 31));
        vision2_2->setAlignment(Qt::AlignCenter);
        vision8_2 = new QLabel(CtrlVisionLifesignalForm);
        vision8_2->setObjectName(QString::fromUtf8("vision8_2"));
        vision8_2->setGeometry(QRect(330, 250, 71, 31));
        vision8_2->setAlignment(Qt::AlignCenter);
        vision5_2 = new QLabel(CtrlVisionLifesignalForm);
        vision5_2->setObjectName(QString::fromUtf8("vision5_2"));
        vision5_2->setGeometry(QRect(330, 160, 71, 31));
        vision5_2->setAlignment(Qt::AlignCenter);
        name1_2 = new QLabel(CtrlVisionLifesignalForm);
        name1_2->setObjectName(QString::fromUtf8("name1_2"));
        name1_2->setGeometry(QRect(240, 40, 91, 31));
        name1_2->setAlignment(Qt::AlignCenter);
        lifesignal7_2 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal7_2->setObjectName(QString::fromUtf8("lifesignal7_2"));
        lifesignal7_2->setGeometry(QRect(400, 220, 61, 31));
        lifesignal7_2->setAlignment(Qt::AlignCenter);
        lifesignal5_3 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal5_3->setObjectName(QString::fromUtf8("lifesignal5_3"));
        lifesignal5_3->setGeometry(QRect(620, 160, 61, 31));
        lifesignal5_3->setAlignment(Qt::AlignCenter);
        lifesignal6_3 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal6_3->setObjectName(QString::fromUtf8("lifesignal6_3"));
        lifesignal6_3->setGeometry(QRect(620, 190, 61, 31));
        lifesignal6_3->setAlignment(Qt::AlignCenter);
        name8_3 = new QLabel(CtrlVisionLifesignalForm);
        name8_3->setObjectName(QString::fromUtf8("name8_3"));
        name8_3->setGeometry(QRect(460, 250, 91, 31));
        name8_3->setAlignment(Qt::AlignCenter);
        vision4_3 = new QLabel(CtrlVisionLifesignalForm);
        vision4_3->setObjectName(QString::fromUtf8("vision4_3"));
        vision4_3->setGeometry(QRect(550, 130, 71, 31));
        vision4_3->setAlignment(Qt::AlignCenter);
        lifesignal8_3 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal8_3->setObjectName(QString::fromUtf8("lifesignal8_3"));
        lifesignal8_3->setGeometry(QRect(620, 250, 61, 31));
        lifesignal8_3->setAlignment(Qt::AlignCenter);
        name7_3 = new QLabel(CtrlVisionLifesignalForm);
        name7_3->setObjectName(QString::fromUtf8("name7_3"));
        name7_3->setGeometry(QRect(460, 220, 91, 31));
        name7_3->setAlignment(Qt::AlignCenter);
        vision3_3 = new QLabel(CtrlVisionLifesignalForm);
        vision3_3->setObjectName(QString::fromUtf8("vision3_3"));
        vision3_3->setGeometry(QRect(550, 100, 71, 31));
        vision3_3->setAlignment(Qt::AlignCenter);
        lifesignal1_3 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal1_3->setObjectName(QString::fromUtf8("lifesignal1_3"));
        lifesignal1_3->setGeometry(QRect(620, 40, 61, 31));
        lifesignal1_3->setAlignment(Qt::AlignCenter);
        name4_3 = new QLabel(CtrlVisionLifesignalForm);
        name4_3->setObjectName(QString::fromUtf8("name4_3"));
        name4_3->setGeometry(QRect(460, 130, 91, 31));
        name4_3->setAlignment(Qt::AlignCenter);
        name6_3 = new QLabel(CtrlVisionLifesignalForm);
        name6_3->setObjectName(QString::fromUtf8("name6_3"));
        name6_3->setGeometry(QRect(460, 190, 91, 31));
        name6_3->setAlignment(Qt::AlignCenter);
        lifesignal3_3 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal3_3->setObjectName(QString::fromUtf8("lifesignal3_3"));
        lifesignal3_3->setGeometry(QRect(620, 100, 61, 31));
        lifesignal3_3->setAlignment(Qt::AlignCenter);
        vision6_3 = new QLabel(CtrlVisionLifesignalForm);
        vision6_3->setObjectName(QString::fromUtf8("vision6_3"));
        vision6_3->setGeometry(QRect(550, 190, 71, 31));
        vision6_3->setAlignment(Qt::AlignCenter);
        vision7_3 = new QLabel(CtrlVisionLifesignalForm);
        vision7_3->setObjectName(QString::fromUtf8("vision7_3"));
        vision7_3->setGeometry(QRect(550, 220, 71, 31));
        vision7_3->setAlignment(Qt::AlignCenter);
        lifesignal2_3 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal2_3->setObjectName(QString::fromUtf8("lifesignal2_3"));
        lifesignal2_3->setGeometry(QRect(620, 70, 61, 31));
        lifesignal2_3->setAlignment(Qt::AlignCenter);
        lifesignal4_3 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal4_3->setObjectName(QString::fromUtf8("lifesignal4_3"));
        lifesignal4_3->setGeometry(QRect(620, 130, 61, 31));
        lifesignal4_3->setAlignment(Qt::AlignCenter);
        name5_3 = new QLabel(CtrlVisionLifesignalForm);
        name5_3->setObjectName(QString::fromUtf8("name5_3"));
        name5_3->setGeometry(QRect(460, 160, 91, 31));
        name5_3->setAlignment(Qt::AlignCenter);
        vision1_3 = new QLabel(CtrlVisionLifesignalForm);
        vision1_3->setObjectName(QString::fromUtf8("vision1_3"));
        vision1_3->setGeometry(QRect(550, 40, 71, 31));
        vision1_3->setAlignment(Qt::AlignCenter);
        name3_3 = new QLabel(CtrlVisionLifesignalForm);
        name3_3->setObjectName(QString::fromUtf8("name3_3"));
        name3_3->setGeometry(QRect(460, 100, 91, 31));
        name3_3->setAlignment(Qt::AlignCenter);
        name2_3 = new QLabel(CtrlVisionLifesignalForm);
        name2_3->setObjectName(QString::fromUtf8("name2_3"));
        name2_3->setGeometry(QRect(460, 70, 91, 31));
        name2_3->setAlignment(Qt::AlignCenter);
        vision2_3 = new QLabel(CtrlVisionLifesignalForm);
        vision2_3->setObjectName(QString::fromUtf8("vision2_3"));
        vision2_3->setGeometry(QRect(550, 70, 71, 31));
        vision2_3->setAlignment(Qt::AlignCenter);
        vision8_3 = new QLabel(CtrlVisionLifesignalForm);
        vision8_3->setObjectName(QString::fromUtf8("vision8_3"));
        vision8_3->setGeometry(QRect(550, 250, 71, 31));
        vision8_3->setAlignment(Qt::AlignCenter);
        vision5_3 = new QLabel(CtrlVisionLifesignalForm);
        vision5_3->setObjectName(QString::fromUtf8("vision5_3"));
        vision5_3->setGeometry(QRect(550, 160, 71, 31));
        vision5_3->setAlignment(Qt::AlignCenter);
        name1_3 = new QLabel(CtrlVisionLifesignalForm);
        name1_3->setObjectName(QString::fromUtf8("name1_3"));
        name1_3->setGeometry(QRect(460, 40, 91, 31));
        name1_3->setAlignment(Qt::AlignCenter);
        lifesignal7_3 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal7_3->setObjectName(QString::fromUtf8("lifesignal7_3"));
        lifesignal7_3->setGeometry(QRect(620, 220, 61, 31));
        lifesignal7_3->setAlignment(Qt::AlignCenter);
        name9 = new QLabel(CtrlVisionLifesignalForm);
        name9->setObjectName(QString::fromUtf8("name9"));
        name9->setGeometry(QRect(20, 280, 91, 31));
        name9->setAlignment(Qt::AlignCenter);
        vision9 = new QLabel(CtrlVisionLifesignalForm);
        vision9->setObjectName(QString::fromUtf8("vision9"));
        vision9->setGeometry(QRect(110, 280, 71, 31));
        vision9->setAlignment(Qt::AlignCenter);
        vision9_2 = new QLabel(CtrlVisionLifesignalForm);
        vision9_2->setObjectName(QString::fromUtf8("vision9_2"));
        vision9_2->setGeometry(QRect(330, 280, 71, 31));
        vision9_2->setAlignment(Qt::AlignCenter);
        vision9_3 = new QLabel(CtrlVisionLifesignalForm);
        vision9_3->setObjectName(QString::fromUtf8("vision9_3"));
        vision9_3->setGeometry(QRect(550, 280, 71, 31));
        vision9_3->setAlignment(Qt::AlignCenter);
        name9_2 = new QLabel(CtrlVisionLifesignalForm);
        name9_2->setObjectName(QString::fromUtf8("name9_2"));
        name9_2->setGeometry(QRect(240, 280, 91, 31));
        name9_2->setAlignment(Qt::AlignCenter);
        lifesignal9_2 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal9_2->setObjectName(QString::fromUtf8("lifesignal9_2"));
        lifesignal9_2->setGeometry(QRect(400, 280, 61, 31));
        lifesignal9_2->setAlignment(Qt::AlignCenter);
        lifesignal9 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal9->setObjectName(QString::fromUtf8("lifesignal9"));
        lifesignal9->setGeometry(QRect(180, 280, 61, 31));
        lifesignal9->setAlignment(Qt::AlignCenter);
        lifesignal9_3 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal9_3->setObjectName(QString::fromUtf8("lifesignal9_3"));
        lifesignal9_3->setGeometry(QRect(620, 280, 61, 31));
        lifesignal9_3->setAlignment(Qt::AlignCenter);
        name9_3 = new QLabel(CtrlVisionLifesignalForm);
        name9_3->setObjectName(QString::fromUtf8("name9_3"));
        name9_3->setGeometry(QRect(460, 280, 91, 31));
        name9_3->setAlignment(Qt::AlignCenter);
        name10 = new QLabel(CtrlVisionLifesignalForm);
        name10->setObjectName(QString::fromUtf8("name10"));
        name10->setGeometry(QRect(20, 310, 91, 31));
        name10->setAlignment(Qt::AlignCenter);
        vision10 = new QLabel(CtrlVisionLifesignalForm);
        vision10->setObjectName(QString::fromUtf8("vision10"));
        vision10->setGeometry(QRect(110, 310, 71, 31));
        vision10->setAlignment(Qt::AlignCenter);
        vision10_2 = new QLabel(CtrlVisionLifesignalForm);
        vision10_2->setObjectName(QString::fromUtf8("vision10_2"));
        vision10_2->setGeometry(QRect(330, 310, 71, 31));
        vision10_2->setAlignment(Qt::AlignCenter);
        vision10_3 = new QLabel(CtrlVisionLifesignalForm);
        vision10_3->setObjectName(QString::fromUtf8("vision10_3"));
        vision10_3->setGeometry(QRect(550, 310, 71, 31));
        vision10_3->setAlignment(Qt::AlignCenter);
        name10_2 = new QLabel(CtrlVisionLifesignalForm);
        name10_2->setObjectName(QString::fromUtf8("name10_2"));
        name10_2->setGeometry(QRect(240, 310, 91, 31));
        name10_2->setAlignment(Qt::AlignCenter);
        lifesignal10_2 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal10_2->setObjectName(QString::fromUtf8("lifesignal10_2"));
        lifesignal10_2->setGeometry(QRect(400, 310, 61, 31));
        lifesignal10_2->setAlignment(Qt::AlignCenter);
        lifesignal10 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal10->setObjectName(QString::fromUtf8("lifesignal10"));
        lifesignal10->setGeometry(QRect(180, 310, 61, 31));
        lifesignal10->setAlignment(Qt::AlignCenter);
        lifesignal10_3 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal10_3->setObjectName(QString::fromUtf8("lifesignal10_3"));
        lifesignal10_3->setGeometry(QRect(620, 310, 61, 31));
        lifesignal10_3->setAlignment(Qt::AlignCenter);
        name10_3 = new QLabel(CtrlVisionLifesignalForm);
        name10_3->setObjectName(QString::fromUtf8("name10_3"));
        name10_3->setGeometry(QRect(460, 310, 91, 31));
        name10_3->setAlignment(Qt::AlignCenter);
        name11 = new QLabel(CtrlVisionLifesignalForm);
        name11->setObjectName(QString::fromUtf8("name11"));
        name11->setGeometry(QRect(20, 340, 91, 31));
        name11->setAlignment(Qt::AlignCenter);
        lifesignal11 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal11->setObjectName(QString::fromUtf8("lifesignal11"));
        lifesignal11->setGeometry(QRect(180, 340, 61, 31));
        lifesignal11->setAlignment(Qt::AlignCenter);
        vision11 = new QLabel(CtrlVisionLifesignalForm);
        vision11->setObjectName(QString::fromUtf8("vision11"));
        vision11->setGeometry(QRect(110, 340, 71, 31));
        vision11->setAlignment(Qt::AlignCenter);
        name12 = new QLabel(CtrlVisionLifesignalForm);
        name12->setObjectName(QString::fromUtf8("name12"));
        name12->setGeometry(QRect(20, 370, 91, 31));
        name12->setAlignment(Qt::AlignCenter);
        lifesignal12 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal12->setObjectName(QString::fromUtf8("lifesignal12"));
        lifesignal12->setGeometry(QRect(180, 370, 61, 31));
        lifesignal12->setAlignment(Qt::AlignCenter);
        vision12 = new QLabel(CtrlVisionLifesignalForm);
        vision12->setObjectName(QString::fromUtf8("vision12"));
        vision12->setGeometry(QRect(110, 370, 71, 31));
        vision12->setAlignment(Qt::AlignCenter);
        name11_2 = new QLabel(CtrlVisionLifesignalForm);
        name11_2->setObjectName(QString::fromUtf8("name11_2"));
        name11_2->setGeometry(QRect(240, 340, 91, 31));
        name11_2->setAlignment(Qt::AlignCenter);
        vision12_2 = new QLabel(CtrlVisionLifesignalForm);
        vision12_2->setObjectName(QString::fromUtf8("vision12_2"));
        vision12_2->setGeometry(QRect(330, 370, 71, 31));
        vision12_2->setAlignment(Qt::AlignCenter);
        lifesignal12_2 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal12_2->setObjectName(QString::fromUtf8("lifesignal12_2"));
        lifesignal12_2->setGeometry(QRect(400, 370, 61, 31));
        lifesignal12_2->setAlignment(Qt::AlignCenter);
        vision11_2 = new QLabel(CtrlVisionLifesignalForm);
        vision11_2->setObjectName(QString::fromUtf8("vision11_2"));
        vision11_2->setGeometry(QRect(330, 340, 71, 31));
        vision11_2->setAlignment(Qt::AlignCenter);
        name12_2 = new QLabel(CtrlVisionLifesignalForm);
        name12_2->setObjectName(QString::fromUtf8("name12_2"));
        name12_2->setGeometry(QRect(240, 370, 91, 31));
        name12_2->setAlignment(Qt::AlignCenter);
        lifesignal11_2 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal11_2->setObjectName(QString::fromUtf8("lifesignal11_2"));
        lifesignal11_2->setGeometry(QRect(400, 340, 61, 31));
        lifesignal11_2->setAlignment(Qt::AlignCenter);
        name11_3 = new QLabel(CtrlVisionLifesignalForm);
        name11_3->setObjectName(QString::fromUtf8("name11_3"));
        name11_3->setGeometry(QRect(460, 340, 91, 31));
        name11_3->setAlignment(Qt::AlignCenter);
        vision12_3 = new QLabel(CtrlVisionLifesignalForm);
        vision12_3->setObjectName(QString::fromUtf8("vision12_3"));
        vision12_3->setGeometry(QRect(550, 370, 71, 31));
        vision12_3->setAlignment(Qt::AlignCenter);
        lifesignal12_3 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal12_3->setObjectName(QString::fromUtf8("lifesignal12_3"));
        lifesignal12_3->setGeometry(QRect(620, 370, 61, 31));
        lifesignal12_3->setAlignment(Qt::AlignCenter);
        vision11_3 = new QLabel(CtrlVisionLifesignalForm);
        vision11_3->setObjectName(QString::fromUtf8("vision11_3"));
        vision11_3->setGeometry(QRect(550, 340, 71, 31));
        vision11_3->setAlignment(Qt::AlignCenter);
        name12_3 = new QLabel(CtrlVisionLifesignalForm);
        name12_3->setObjectName(QString::fromUtf8("name12_3"));
        name12_3->setGeometry(QRect(460, 370, 91, 31));
        name12_3->setAlignment(Qt::AlignCenter);
        lifesignal11_3 = new QLabel(CtrlVisionLifesignalForm);
        lifesignal11_3->setObjectName(QString::fromUtf8("lifesignal11_3"));
        lifesignal11_3->setGeometry(QRect(620, 340, 61, 31));
        lifesignal11_3->setAlignment(Qt::AlignCenter);

        retranslateUi(CtrlVisionLifesignalForm);

        QMetaObject::connectSlotsByName(CtrlVisionLifesignalForm);
    } // setupUi

    void retranslateUi(QWidget *CtrlVisionLifesignalForm)
    {
        CtrlVisionLifesignalForm->setWindowTitle(QApplication::translate("CtrlVisionLifesignalForm", "Form", 0, QApplication::UnicodeUTF8));
        name1->setText(QApplication::translate("CtrlVisionLifesignalForm", "1", 0, QApplication::UnicodeUTF8));
        vision1->setText(QString());
        lifesignal1->setText(QString());
        label3->setText(QApplication::translate("CtrlVisionLifesignalForm", " \347\224\237\345\221\275\344\277\241\345\217\267", 0, QApplication::UnicodeUTF8));
        label2->setText(QApplication::translate("CtrlVisionLifesignalForm", "\347\211\210\346\234\254\345\217\267", 0, QApplication::UnicodeUTF8));
        label1->setText(QApplication::translate("CtrlVisionLifesignalForm", "\350\256\276\345\244\207", 0, QApplication::UnicodeUTF8));
        label6->setText(QApplication::translate("CtrlVisionLifesignalForm", " \347\224\237\345\221\275\344\277\241\345\217\267", 0, QApplication::UnicodeUTF8));
        label5->setText(QApplication::translate("CtrlVisionLifesignalForm", "\347\211\210\346\234\254\345\217\267", 0, QApplication::UnicodeUTF8));
        label4->setText(QApplication::translate("CtrlVisionLifesignalForm", "\350\256\276\345\244\207", 0, QApplication::UnicodeUTF8));
        label9->setText(QApplication::translate("CtrlVisionLifesignalForm", " \347\224\237\345\221\275\344\277\241\345\217\267", 0, QApplication::UnicodeUTF8));
        label8->setText(QApplication::translate("CtrlVisionLifesignalForm", "\347\211\210\346\234\254\345\217\267", 0, QApplication::UnicodeUTF8));
        label7->setText(QApplication::translate("CtrlVisionLifesignalForm", "\350\256\276\345\244\207", 0, QApplication::UnicodeUTF8));
        lifesignal2->setText(QString());
        vision2->setText(QString());
        name2->setText(QApplication::translate("CtrlVisionLifesignalForm", "2", 0, QApplication::UnicodeUTF8));
        lifesignal3->setText(QString());
        vision3->setText(QString());
        name3->setText(QApplication::translate("CtrlVisionLifesignalForm", "3", 0, QApplication::UnicodeUTF8));
        lifesignal4->setText(QString());
        vision4->setText(QString());
        name4->setText(QApplication::translate("CtrlVisionLifesignalForm", "4", 0, QApplication::UnicodeUTF8));
        lifesignal5->setText(QString());
        vision5->setText(QString());
        name5->setText(QApplication::translate("CtrlVisionLifesignalForm", "5", 0, QApplication::UnicodeUTF8));
        lifesignal6->setText(QString());
        vision6->setText(QString());
        name6->setText(QApplication::translate("CtrlVisionLifesignalForm", "6", 0, QApplication::UnicodeUTF8));
        lifesignal7->setText(QString());
        vision7->setText(QString());
        name7->setText(QApplication::translate("CtrlVisionLifesignalForm", "7", 0, QApplication::UnicodeUTF8));
        lifesignal8->setText(QString());
        vision8->setText(QString());
        name8->setText(QApplication::translate("CtrlVisionLifesignalForm", "8", 0, QApplication::UnicodeUTF8));
        lifesignal5_2->setText(QString());
        lifesignal6_2->setText(QString());
        name8_2->setText(QApplication::translate("CtrlVisionLifesignalForm", "8", 0, QApplication::UnicodeUTF8));
        vision4_2->setText(QString());
        lifesignal8_2->setText(QString());
        name7_2->setText(QApplication::translate("CtrlVisionLifesignalForm", "7", 0, QApplication::UnicodeUTF8));
        vision3_2->setText(QString());
        lifesignal1_2->setText(QString());
        name4_2->setText(QApplication::translate("CtrlVisionLifesignalForm", "4", 0, QApplication::UnicodeUTF8));
        name6_2->setText(QApplication::translate("CtrlVisionLifesignalForm", "6", 0, QApplication::UnicodeUTF8));
        lifesignal3_2->setText(QString());
        vision6_2->setText(QString());
        vision7_2->setText(QString());
        lifesignal2_2->setText(QString());
        lifesignal4_2->setText(QString());
        name5_2->setText(QApplication::translate("CtrlVisionLifesignalForm", "5", 0, QApplication::UnicodeUTF8));
        vision1_2->setText(QString());
        name3_2->setText(QApplication::translate("CtrlVisionLifesignalForm", "3", 0, QApplication::UnicodeUTF8));
        name2_2->setText(QApplication::translate("CtrlVisionLifesignalForm", "2", 0, QApplication::UnicodeUTF8));
        vision2_2->setText(QString());
        vision8_2->setText(QString());
        vision5_2->setText(QString());
        name1_2->setText(QApplication::translate("CtrlVisionLifesignalForm", "1", 0, QApplication::UnicodeUTF8));
        lifesignal7_2->setText(QString());
        lifesignal5_3->setText(QString());
        lifesignal6_3->setText(QString());
        name8_3->setText(QApplication::translate("CtrlVisionLifesignalForm", "8", 0, QApplication::UnicodeUTF8));
        vision4_3->setText(QString());
        lifesignal8_3->setText(QString());
        name7_3->setText(QApplication::translate("CtrlVisionLifesignalForm", "7", 0, QApplication::UnicodeUTF8));
        vision3_3->setText(QString());
        lifesignal1_3->setText(QString());
        name4_3->setText(QApplication::translate("CtrlVisionLifesignalForm", "4", 0, QApplication::UnicodeUTF8));
        name6_3->setText(QApplication::translate("CtrlVisionLifesignalForm", "6", 0, QApplication::UnicodeUTF8));
        lifesignal3_3->setText(QString());
        vision6_3->setText(QString());
        vision7_3->setText(QString());
        lifesignal2_3->setText(QString());
        lifesignal4_3->setText(QString());
        name5_3->setText(QApplication::translate("CtrlVisionLifesignalForm", "5", 0, QApplication::UnicodeUTF8));
        vision1_3->setText(QString());
        name3_3->setText(QApplication::translate("CtrlVisionLifesignalForm", "3", 0, QApplication::UnicodeUTF8));
        name2_3->setText(QApplication::translate("CtrlVisionLifesignalForm", "2", 0, QApplication::UnicodeUTF8));
        vision2_3->setText(QString());
        vision8_3->setText(QString());
        vision5_3->setText(QString());
        name1_3->setText(QApplication::translate("CtrlVisionLifesignalForm", "1", 0, QApplication::UnicodeUTF8));
        lifesignal7_3->setText(QString());
        name9->setText(QApplication::translate("CtrlVisionLifesignalForm", "9", 0, QApplication::UnicodeUTF8));
        vision9->setText(QString());
        vision9_2->setText(QString());
        vision9_3->setText(QString());
        name9_2->setText(QApplication::translate("CtrlVisionLifesignalForm", "9", 0, QApplication::UnicodeUTF8));
        lifesignal9_2->setText(QString());
        lifesignal9->setText(QString());
        lifesignal9_3->setText(QString());
        name9_3->setText(QApplication::translate("CtrlVisionLifesignalForm", "9", 0, QApplication::UnicodeUTF8));
        name10->setText(QApplication::translate("CtrlVisionLifesignalForm", "10", 0, QApplication::UnicodeUTF8));
        vision10->setText(QString());
        vision10_2->setText(QString());
        vision10_3->setText(QString());
        name10_2->setText(QApplication::translate("CtrlVisionLifesignalForm", "10", 0, QApplication::UnicodeUTF8));
        lifesignal10_2->setText(QString());
        lifesignal10->setText(QString());
        lifesignal10_3->setText(QString());
        name10_3->setText(QApplication::translate("CtrlVisionLifesignalForm", "10", 0, QApplication::UnicodeUTF8));
        name11->setText(QApplication::translate("CtrlVisionLifesignalForm", "11", 0, QApplication::UnicodeUTF8));
        lifesignal11->setText(QString());
        vision11->setText(QString());
        name12->setText(QApplication::translate("CtrlVisionLifesignalForm", "12", 0, QApplication::UnicodeUTF8));
        lifesignal12->setText(QString());
        vision12->setText(QString());
        name11_2->setText(QApplication::translate("CtrlVisionLifesignalForm", "11", 0, QApplication::UnicodeUTF8));
        vision12_2->setText(QString());
        lifesignal12_2->setText(QString());
        vision11_2->setText(QString());
        name12_2->setText(QApplication::translate("CtrlVisionLifesignalForm", "12", 0, QApplication::UnicodeUTF8));
        lifesignal11_2->setText(QString());
        name11_3->setText(QApplication::translate("CtrlVisionLifesignalForm", "11", 0, QApplication::UnicodeUTF8));
        vision12_3->setText(QString());
        lifesignal12_3->setText(QString());
        vision11_3->setText(QString());
        name12_3->setText(QApplication::translate("CtrlVisionLifesignalForm", "12", 0, QApplication::UnicodeUTF8));
        lifesignal11_3->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class CtrlVisionLifesignalForm: public Ui_CtrlVisionLifesignalForm {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CTRLVISIONLIFESIGNALFORM_H
